//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kebas
{
	using System;
	
	
	public interface _SyntaxEnd
	{
	}
	
	public class _OsdBuilderSyntax : OsdBuilderSyntax, NamedSyntax, DescribedSyntax
	{
	}
	
	public interface OsdBuilderSyntax
	{
	}
	
	public sealed class OsdBuilderData
	{
	}
	
	public interface NamedSyntax : _SyntaxEnd
	{
	}
	
	public sealed class NamedData
	{
	}
	
	public interface DescribedSyntax : _SyntaxEnd
	{
	}
	
	public sealed class DescribedData
	{
	}
}
